<?
	
	require "lang/english.php";
	
	country_drop('india');
//showing country drop-down list
function country_drop($val)	
{
	if(empty($val))	$val=LNG_US;
	
	$country=array(LNG_AFGAN,LNG_ALBANIA,LNG_ALGERIA,LNG_AS,LNG_ANDORRA,LNG_ANGOLA,LNG_ANGUILIA,LNG_ANTERTICA,LNG_AB,LNG_ARGENTINA,LNG_ARMENIA,LNG_ARUBA,LNG_AI,LNG_AUSTRALIA,LNG_AUSTRIA,LNG_AZ,LNG_BAHAMAS,LNG_BAHRAIN,LNG_BANGLADESH,LNG_BARBADOS,LNG_BELARUS,LNG_BELGIUM,LNG_BELIZE,LNG_BENIN,LNG_BERMUDA,LNG_BHUTAN,LNG_BOLIVIA,LNG_BOTSWANA,LNG_BI,LNG_BRAZIL,LNG_BD,LNG_BULGARIA,LNG_B_FASO,LNG_BURUNDI,LNG_CAMBODIA,LNG_CAMEROON,LNG_CANADA,LNG_CVI,LNG_CI,LNG_CHAD,LNG_CHILE,LNG_CHINA,LNG_C_ILAND,LNG_COLOMBIA,LNG_COMOROS,LNG_CRO,LNG_COOK_I,LNG_COSTA_RICA,LNG_COTE_D_IVOIRE,LNG_CROATIA,LNG_CYPRUS,LNG_CZECH,LNG_DENMARK,LNG_DJBOUTI,LNG_DOMINICA,LNG_DOMINICAN,LNG_EAST_TIMOR,LNG_ECUADOR,LNG_EGYPT,LNG_EL_SALVA,LNG_EQ_GUINEA,LNG_ERITREA,LNG_ESTONIA,LNG_ETHIOP,LNG_FALKAN_IS,LNG_FAROE,LNG_FIJI,LNG_FINLAND,LNG_FRANCE,LNG_FRENCHG,LNG_FRENCHP,LNG_GABON,LNG_GAMBIA,LNG_GEORGIA,LNG_GERMANY,LNG_GHANA,LNG_GIBRA,LNG_GREECE,LNG_GREENLND,LNG_GRENADA,LNG_GUADE,LNG_GUAM,LNG_GAUTE,LNG_GUERNSEY,LNG_GUINEA,LNG_GUINEAB,LNG_GUYANA,LNG_HAITI,LNG_HONDU,LNG_HK,LNG_HUNGARY,LNG_ICELAND,LNG_INDIA,LNG_INDONES,LNG_IRAN,LNG_IRELAND,LNG_ISLEMAN,LNG_ISRAEL,LNG_ITALY,LNG_JAMAICA,LNG_JAPAN,LNG_JERSEY,LNG_JORDAN,LNG_KAZAK,LNG_KENYA,LNG_KIRIBA,LNG_KORIA_REP,LNG_KUWAIT,LNG_KYRGY,LNG_LAOS,LNG_LAT,LNG_LEBANON,LNG_LESOTHO,LNG_LIBERIA,LNG_LIBYA,LNG_LIECHT,LNG_LIHU,LNG_LUXEM,LNG_MACAU,LNG_MACEDONIA,LNG_MADAGASCAR,LNG_MALAWI,LNG_MALAY,LNG_MALDIVES,LNG_MALI,LNG_MALTA,LNG_MARSHAL_IS,LNG_MARTINI,LNG_MAURITANIA,LNG_MAURI,LNG_MAYOTTE_IS,LNG_MEXICO,LNG_MICRONESIA,LNG_MOLDOVA,LNG_MONACO,LNG_MONGOL,LNG_MONTS,LNG_MOROCO,LNG_MOZAMBQ,LNG_MYANMAR,LNG_NAMBIA,LNG_NAURU,LNG_NEPAL,LNG_NETH,LNG_NETH_ANTI,LNG_NEWCALE,LNG_NEWZEA,LNG_NICAR,LNG_NIGER,LNG_NIGERIA,LNG_NIUE,LNG_NORFOLK_IS,LNG_NORWAY,LNG_OMAN,LNG_PAKI,LNG_PALAU,LNG_PANAMA,LNG_PAPUA,LNG_PARAGUAY,LNG_PERU,LNG_PHILIPS,LNG_PITC_IS,LNG_POLAND,LNG_PORTUGAL,LNG_PUERTO_RICO,LNG_QATAR,LNG_REUNION_IS,LNG_ROMANIA,LNG_RUSS_FED,LNG_RAWANDA,LNG_SAINTHELENA,LNG_SAINTLUCIA,LNG_SANMARINO,LNG_SARAB,LNG_SENGAL,LNG_SEYCHELL,LNG_SIERA_LE,LNG_SPORE,LNG_SLOV_REP,LNG_SOLVE,LNG_SOLO_IL,LNG_SOMALIA,LNG_SAFRICA,LNG_SGEORGIA,LNG_SPAIN,LNG_LANKA,LNG_SURINAM,LNG_SVALB,LNG_SWAZI,LNG_SWEDEN,LNG_SWITZ,LNG_SYRIA,LNG_TAIWAN,LNG_TAJIK,LNG_TANZ,LNG_THAI,LNG_TOGO,LNG_TOKELAU,LNG_TONGAI,LNG_TUNISI,LNG_TURKEY,LNG_TURKMS,LNG_TUVALU,LNG_UGND,LNG_UKRN,LNG_UK,LNG_USA,LNG_URUGUA,LNG_UZBEK,LNG_VANUA,LNG_VATI,LNG_VENEZ,LNG_VIET,LNG_WSHARA,LNG_WSAMO,LNG_YEMEN,LNG_YUGO,LNG_ZAMB,LNG_ZIMB);
	
	for($i=0; $i<=count($country)-1; $i++)	{
?>
		<option value="<?=$country[$i]?>"<? echo selected($country[$i],$val); ?>><?=$country[$i]?></option>
<?
	}
}
	
	
	echo $country;
?>	
